apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - istio-namespaces
  - istio-base
  - istiod
  - istio-ingress
  - cert-manager
  - crossplane
  - nginx-ingress
  - private
