apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tls-ingress-xr
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/mujak27/k8s-crossplane
    targetRevision: main
    path: crossplane/01-tls-ingress/xr
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
